site_name: "ess-techdocs"
site_description: "ESS Technical Documentation"
docs_dir: "docs"
repo_url: https://github.com/bcgov/event-stream-service-techdocs
edit_uri: edit/main/docs/
plugins:
  - techdocs-core
  - ezlinks

markdown_extensions:
  - attr_list
  - md_in_html
  - mkpatcher:
      location: patcher.py
nav:
  - Home: index.md
  - About ESS: About.md
  - Capabilities:
      - Functionalities: Capabilities/Functionalities.md
      - Integrations: Capabilities/Integrations.md
      - Data Management: Capabilities/Data-Management.md
  - Components:
      - Event Stream Service: Components/Event-Stream-Service.md
      - Event Stream Service API: Components/Event-Stream-Service-API.md
      - Event Stream Service UI: Components/Event-Stream-Service-UI.md
      - Event Stream Service CLI: Components/Event-Stream-Service-CLI.md
  - Developer:
      - Contributors: Developer/Contributors.md
      - Deployment: Developer/Deployment.md
